baseURL = "https://hn.otoh.org"
languageCode = "en-au"
title = "Honduras Bay Islands COVID-19 Resources"
theme = "noteworthy"
enableRobotsTXT = false
paginate = 10 # The number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure length of homepage summary

# Add your Google Analytics identifier: UA-XXXXXXXX-X
#googleAnalytics = "" 

# Add your Disqus shortname here.
#disqusShortname = ""    

[taxonomies]
  tag = "tags"

[author]
  name = "Paul Armstrong"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = false

[params]
  math = true
  # Blog description at the top of the homepage. Supports markdown.
  description = "COVID-19 resources for Utila and the Honduran Bay Islands"
  github = "https://github.com/psa/hn.otoh.org"

# Menu links along the sidebar navigation.
# Weight is an integer used to sort the menu items. The sorting goes from
# smallest to largest numbers. If weight is not defined for each menu entry,
# Hugo will sort the entries alphabetically.

[[menu.main]]
  identifier = 'make-it-count'
  name = "Donation: Make it Count"
  url = 'https://themakeitcountfoundation.org/'
  weight = 0

[[menu.main]]
  identifier = 'sol-foundation'
  name = "Donation: Sol Foundation"
  url = 'https://www.solroatan.org/'
  weight = 0

[[menu.main]]
  identifier = 'support-utila
  name = "Donation: Support Utila"
  url = 'http://www.SupportUtila.org'
  weight = 0

[[menu.main]]
  identifier = 'official-sites'
  name = "Official Websites"
  url = '/official-sites/'
  weight = 1

[[menu.main]]
  identifier = 'whatsapp'
  name = "WhatsApp Groups (mostly flights)"
  url = '/whatsapp/'
  weight = 2

[[menu.main]]
  identifier = 'curfew'
  name = 'Curfew'
  url = '/curfew/'
  weight = 3

[[menu.main]]
  identifier = 'bay-islands-governor'
  name = "Governer Summaries"
  url = '/tags/bay-islands-governor/'
  weight = 10

[[menu.main]]
  identifier = 'utila-mayor'
  name = "Utila Mayor Summaries"
  url = '/tags/utila-mayor/'
  weight = 10

[[menu.main]]
  identifier = 'utila-groceries'
  name = "Utila Groceries and Services"
  url = '/utila-groceries/'
  weight = 11

[[menu.main]]
  identifier = 'utila-restaurants'
  name = "Utila Restaurants"
  url = '/utila-restaurants/'
  weight = 12

[[menu.main]]
  identifier = "expat-registration"
  name = "Expat Registration"
  url = "/expat-registration/"
  weight = 98

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 98

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 99

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = true
